Traceback (most recent call last):
  File "./ST_hdf5_dataset_creation.py", line 2, in <module>
    import h5py
  File "/opt/apps/intel18/impi18_0/python3/3.7.0/lib/python3.7/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: libhdf5.so.10: cannot open shared object file: No such file or directory
